# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
