# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_app', '0003_bookmark_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
